# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4
clone:
  depth: full
pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
#          - npm test
    - step:
        # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
        # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
        name: Deploy to Heroku
        deployment: test   # set to test, staging or production
        # trigger: manual  # uncomment to have a manual step
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
  custom:
    deploy-to-s3:
      - step:
         script:
                    - npm run build
                    # - apt-get update # required to install zip
                    # - apt-get install -y zip # required if you want to zip repository objects
                    - pip install boto3==1.3.0 # required for s3_upload.py
                    # the first argument is the name of the existing S3 bucket to upload the artefact to
                    # the second argument is the artefact to be uploaded
                    # the third argument is the the bucket key
                    - python s3_upload.py bucket artefact bucket_key # run the deployment script
                    # Example command line parameters. Replace with your values
                    #- python s3_upload.py bb-s3-upload SampleApp_Linux.zip SampleApp_Linux # run the deployment script