
GET http://localhost:8080/cve?vulnerable_cpe=avm:fritz&fields=id,cvss,summary HTTP/1.1

###

POST http://localhost:8080/api/v1/cves/search HTTP/1.1
content-type: application/json

{
    "vulnerableCpes": ["cpe:/o:avm:fritz", "cpe:/a:avm:fritz","cpe:/h:avm:fritz", "redhat:linux"],
    "fields": ["id", "vulnerable_product", "summary"],
    "itemsPerPage": 25,
    "requestedPage": 1
}

###

GET http://34.77.225.216:8080/api/v1/stats HTTP/1.1

###



GET http://localhost:8080/api/v1/stats HTTP/1.1

###


###

POST http://localhost:8080/api/v1/cves/search HTTP/1.1
content-type: application/json

{
    "vulnerableCpes": ["cpe:2.3:a:microsoft:windows_xp",
        "cpe:2.3:o:apple:iphone_os",
        "cpe:2.3:a:adobe:acrobat_reader",
        "cpe:2.3:a:microsoft:outlook",
        "cpe:2.3:a:microsoft:.net_framework:",
        "cpe:2.3:a:microsoft",
        "cpe:2.3:o:linux",
        "cpe:2.3:a:redhat"],
    "fields": ["id", "cvss", "references", "Modified", 
        "Published", "summary"],
    "itemsPerPage": 20,
    "requestedPage": 1
}

###

POST http://localhost:8080/api/v1/cves/search HTTP/1.1
content-type: application/json

{
    "vulnerableCpes": [
        "cpe:2.3:o:microsoft:windows_xp"
        ],
    "fields": ["id", "cvss", "vulnerable_product", "vulnerable_configuration"],
    "itemsPerPage": 20,
    "requestedPage": 1
}
###

GET http://localhost:8080/api/v1/cpes/prefix/android HTTP/1.1

###

GET http://localhost:8080/api/v1/cves/vulnerable_product/microsoft?fields=id,cvss,vulnerable_product,vulnerable_configuration HTTP/1.1

###

GET http://localhost:8080/api/v1/cves/summary/vulnerable_product/cpe%3A2.3%3Ao%3Aapple%3Aiphone_os HTTP/1.1

###

GET http://localhost:8080/api/v1/cve/CVE-2014-8872 HTTP/1.1




